#pragma once

#include <stdint.h>

/* The Braino! mark -- GENERATED by tools/gen_logo_mask.py from
 * tools/braino-badge.svg. Do not edit.
 *
 * One-bit silhouettes, bit 7 of each byte leftmost, so they can be
 * painted in any colour the caller likes -- which the screen saver
 * does, in a shade that changes with the rally.
 *
 * BADGE is the whole artwork. WORD and WORD_SMALL are the wordmark
 * alone, at the sizes the product name used to be drawn as text in a
 * font-4 header and a font-2 row; every one of those places draws the
 * mark now. Ui::drawLogo() picks between them. */
namespace LogoMask {

constexpr int16_t BADGE_WIDTH = 109;
constexpr int16_t BADGE_CENTRE = 46;
constexpr int16_t BADGE_HEIGHT = 118;
constexpr int16_t BADGE_BYTES_PER_ROW = 14;
extern const uint8_t BADGE_BITS[BADGE_HEIGHT][BADGE_BYTES_PER_ROW];

constexpr int16_t BADGE_MID_WIDTH = 50;
constexpr int16_t BADGE_MID_CENTRE = 24;
constexpr int16_t BADGE_MID_HEIGHT = 64;
constexpr int16_t BADGE_MID_BYTES_PER_ROW = 7;
extern const uint8_t BADGE_MID_BITS[BADGE_MID_HEIGHT][BADGE_MID_BYTES_PER_ROW];

constexpr int16_t WORD_WIDTH = 103;
constexpr int16_t WORD_CENTRE = 43;
constexpr int16_t WORD_HEIGHT = 26;
constexpr int16_t WORD_BYTES_PER_ROW = 13;
extern const uint8_t WORD_BITS[WORD_HEIGHT][WORD_BYTES_PER_ROW];

constexpr int16_t WORD_SMALL_WIDTH = 53;
constexpr int16_t WORD_SMALL_CENTRE = 15;
constexpr int16_t WORD_SMALL_HEIGHT = 16;
constexpr int16_t WORD_SMALL_BYTES_PER_ROW = 7;
extern const uint8_t WORD_SMALL_BITS[WORD_SMALL_HEIGHT][WORD_SMALL_BYTES_PER_ROW];

constexpr int16_t ICON_WIDTH = 24;
constexpr int16_t ICON_CENTRE = 12;
constexpr int16_t ICON_HEIGHT = 22;
constexpr int16_t ICON_BYTES_PER_ROW = 3;
extern const uint8_t ICON_BITS[ICON_HEIGHT][ICON_BYTES_PER_ROW];

constexpr int16_t ICON_BIG_WIDTH = 62;
constexpr int16_t ICON_BIG_CENTRE = 31;
constexpr int16_t ICON_BIG_HEIGHT = 56;
constexpr int16_t ICON_BIG_BYTES_PER_ROW = 8;
extern const uint8_t ICON_BIG_BITS[ICON_BIG_HEIGHT][ICON_BIG_BYTES_PER_ROW];

}   // namespace LogoMask
