#pragma once

#include <stdint.h>

/* The Braino! badge -- GENERATED by tools/gen_logo_mask.py from
 * tools/braino-badge.svg. Do not edit.
 *
 * A one-bit silhouette of the product mark, bit 7 of each byte
 * leftmost, so it can be painted in any colour the caller likes --
 * which the screen saver does, in a shade that changes with the rally.
 * Ui::drawLogo() is the way to draw it. */
namespace LogoMask {

constexpr int16_t WIDTH = 72;
constexpr int16_t HEIGHT = 90;
constexpr int16_t BYTES_PER_ROW = 9;

extern const uint8_t BITS[HEIGHT][BYTES_PER_ROW];

}   // namespace LogoMask
