#include "AppRuntime.h"

#include <esp_chip_info.h>
#include <string.h>
#include "AppVersion.h"
#include "BuildStamp.h"

/* The boot banner: what this board is and which firmware it is running,
 * printed once from begin(). Kept out of AppRuntime.cpp so the runtime
 * proper is not also the place that describes the hardware. */
void BrainoApp::logBootBanner() {
    logIdentity();
    Serial.printf("[boot] board=%s rot=%d layout=%s (landscape=%d portrait=%d)\n",
                  BOARD.name,
                  (int)board_.displayRotation(),
                  board_.layoutMode() == Board::LayoutMode::Vertical ? "Vertical" : "Horizontal",
                  (int)BOARD.panel.landscapeRotation,
                  (int)BOARD.panel.portraitRotation);
    /* Beside the board line, so a serial log pasted into an issue identifies
     * the firmware that produced it. "Which build was that?" has cost more
     * than one round trip on a bug report. */
    Serial.printf("[boot] build=%s built=%s version=%s\n",
                  BuildStamp::describe(), BuildStamp::builtAt(), BRAINO_VERSION);
    /* The saved SSID is deliberately absent from this line, and from every
     * other Serial write in the tree. A serial log is the one artifact of
     * this device that routinely leaves the house -- pasted into a bug
     * report, captured by whoever plugs a cable in -- and the network's name
     * belongs to the household, not to the firmware. `creds` answers the only
     * question a log needs answered: whether a network is configured at all.
     * The name itself is still on the device, in System Info and the network
     * activity list, where the person reading it is the person holding it. */
    Serial.printf("[boot] ntp=%d creds=%d tzmin=%d\n",
                  (int)board_.ntpEnabled(), (int)board_.hasWifiCredentials(),
                  (int)board_.tzOffsetMinutes());
}

/* WHO AM I, PRINTED BEFORE ANYTHING ELSE CAN GO WRONG.
 *
 * Four boards on one desk, COM numbers that Windows reshuffles on every
 * replug, and a boot banner that only said the board NAME -- which is compiled
 * in, so it reports which firmware is on the chip and not which panel is under
 * it. Between them those cost most of an afternoon: a 2.8-inch board was
 * flashed with the 4-inch build and reported itself as a 4-inch quite
 * happily, and a board nobody had seen before was identified from a firmware
 * image I had put there myself half an hour earlier.
 *
 * The fix is that the device says what it is, from the parts of itself that
 * cannot be wrong:
 *
 *   device the firmware's own id for this board (Board::deviceId()) -- what
 *          tells two identical-looking boards apart. Not the MAC; see below.
 *   chip   model, revision and core count, straight from esp_chip_info().
 *   flash  size as the ROM reports it, not as the profile claims.
 *   panel  the driver this binary was BUILT with, its size, rotation and
 *          backlight pin -- so a wrong-profile flash is visible in one line
 *          instead of being inferred from a photograph of odd colours.
 *   touch  controller and its pins, since a silent panel and a dead digitiser
 *          look identical from across a room.
 *
 * No profile name, no Wi-Fi credential and no player data is printed here --
 * see the note by the Wi-Fi line in logBootBanner(), which is the rule this
 * has to keep. The same facts can be asked for later without a reset; see
 * tickSerialQuery() below. */
void BrainoApp::logIdentity() {
    esp_chip_info_t chip{};
    esp_chip_info(&chip);

    /* THE MAC IS DELIBERATELY NOT HERE. It was, and this line is the one that
     * gets pasted into a public issue, so it published a permanent hardware
     * identifier every time somebody asked for help. `device=` is generated by
     * the firmware, means nothing off this board, and is reissued by a factory
     * reset -- see Board::deviceId(). If you genuinely need the MAC while
     * holding the board, esptool reads it off the chip. */
    Serial.printf("[boot] device=%s "
                  "chip=%s rev=%u cores=%u flash=%luKB psram=%luKB\n",
                  board_.deviceId(),
                  ESP.getChipModel(), (unsigned)ESP.getChipRevision(),
                  (unsigned)chip.cores,
                  (unsigned long)(ESP.getFlashChipSize() / 1024),
                  (unsigned long)(ESP.getPsramSize() / 1024));

    /* THERE IS NO `id=` FIELD HERE, AND THERE MUST NOT BE ONE AGAIN.
     *
     * 5.9.0 read the controller's ID register with three
     * `tft.readcommand8(0x04, n)` calls and printed the answer. It shipped,
     * and it broke the display on two of the seven boards: the panel came up
     * with the top bar crushed into a band at the bottom edge and the rest of
     * the screen never painted -- an address-window symptom, on a board whose
     * loop was meanwhile running at 48fps with a 23ms worst frame, a flat heap
     * and no stall. Every diagnostic said the firmware was healthy, because it
     * was. The corruption was in the panel, put there by the diagnostic.
     *
     * TFT_eSPI's readcommand8() is not a read. It writes 0xD9 -- an
     * undocumented index-register command -- toggles CS mid-sequence, issues
     * the command and clocks a byte back, and it restores neither the address
     * window nor MADCTL. On a panel that answers you get an ID; on a panel
     * whose MISO is not wired back you get whatever the bus floats to AND a
     * controller left mid-command, which the next write inherits.
     *
     * The field was worth nothing even where it appeared to work: across all
     * seven supported boards it only ever answered 00:00:00 (MISO absent) or
     * FF:FF:FF (floating high). Not one returned a real ID. So this was a
     * diagnostic that could not diagnose, paid for with a corrupted panel.
     *
     * If a future board genuinely wires MISO back and the ID is genuinely
     * wanted, it needs a PanelProfile field saying so and a setRotation()
     * reissued afterwards to rebuild the window -- never an unconditional
     * read. Until a board needs it, the correct version of this line is the
     * one that does not touch the panel at all. */
    Serial.printf("[boot] panel=%s%s %dx%d bl=IO%d\n",
                  GUME_PANEL_DRIVER, GUME_PANEL_INVERTED ? "+inv" : "",
                  (int)BOARD.panel.nativeWidth, (int)BOARD.panel.nativeHeight,
                  (int)BOARD.panel.backlightPin);

    Serial.printf("[boot] touch=%s cs=IO%d irq=IO%d sd=%s rgb=%s bat=%s\n",
                  BOARD.touch.kind == TouchKind::CapacitiveFt6336u
                      ? "FT6336U/i2c" : "XPT2046/bitbang",
                  (int)BOARD.touch.cs, (int)BOARD.touch.irq,
                  BOARD.hasSdSlot() ? "yes" : "no",
                  BOARD.hasRgbLed() ? "yes" : "no",
                  BOARD.hasBatterySense() ? "yes" : "no");
}

/* ASKED, NOT RESET: THE SERIAL PORT ANSWERS ONE QUESTION.
 *
 * The boot banner is printed once, at power-up, so the only way to hear it
 * again was to reset the board -- which is what tools/identify_boards.py did
 * to every board on the desk, every time. A reset throws away whatever the
 * board was doing (a game half played, a test another agent was running), and
 * it is not even reliable: one bench board's USB bridge drops off the bus for
 * a moment as the app starts, taking the banner with it, and a 4-inch board
 * reset by its button can refuse to boot at all until it is power-cycled.
 *
 * So a running board answers `braino?` followed by a newline with one line:
 *
 *   [ident] v="1" device="R28T-9F3A2C71" board="E32R28T-1" version="5.10.0"
 *           build="dev @ 1a2b3c4" built="Sep 10 2026 10:00" chip="ESP32-D0WD-V3"
 *           panel="ILI9341_2" up="3605"
 *
 * (one line on the wire; wrapped here). Every value is quoted, because
 * BOARD_NAME and the build time can both contain spaces and the tool once cut
 * a board name off at one. `v` is the format's own version, so a later field
 * can be added without the tool guessing.
 *
 * What it must never become:
 *   - A second way to read player data. The reply is the banner's facts and
 *     nothing else: no profile, no score, no SSID, never the MAC. The same
 *     rules as the banner, for the same reason -- this text gets pasted.
 *   - A command channel. It takes no arguments, changes no state, grants
 *     nothing, and anything that is not exactly the query is dropped. A cable
 *     is local, but the admin PIN would mean nothing if a string on a serial
 *     port could do what the PIN guards.
 *   - Activity. It does not touch lastActivityMs_: a tool polling the desk
 *     must not keep every screen awake, or change what it is testing.
 *
 * Cost: at most QUERY_BYTES_PER_FRAME reads per loop, which with nothing
 * waiting is one Serial.available(). The reply is ~200 bytes, which can block
 * for a few milliseconds while the UART drains -- once, when asked. */
namespace {

constexpr char IDENTIFY_QUERY[] = "braino?";
constexpr size_t IDENTIFY_QUERY_LEN = sizeof(IDENTIFY_QUERY) - 1;
// Room for the query and nothing more; a longer line is not the query.
constexpr size_t QUERY_CAP = IDENTIFY_QUERY_LEN;
constexpr int QUERY_BYTES_PER_FRAME = 32;

char queryBuf[QUERY_CAP];
size_t queryLen = 0;
bool queryOverlong = false;

}  // namespace

void BrainoApp::tickSerialQuery() {
    for (int budget = QUERY_BYTES_PER_FRAME; budget > 0 && Serial.available() > 0;
         --budget) {
        const int c = Serial.read();
        if (c < 0) break;
        if (c == '\r' || c == '\n') {
            const bool match = !queryOverlong && queryLen == IDENTIFY_QUERY_LEN &&
                               memcmp(queryBuf, IDENTIFY_QUERY, IDENTIFY_QUERY_LEN) == 0;
            queryLen = 0;
            queryOverlong = false;
            if (match) replyIdentify();
            continue;
        }
        if (queryLen < QUERY_CAP) {
            queryBuf[queryLen++] = static_cast<char>(c);
        } else {
            queryOverlong = true;
        }
    }
}

void BrainoApp::replyIdentify() {
    Serial.printf("[ident] v=\"1\" device=\"%s\" board=\"%s\" version=\"%s\" "
                  "build=\"%s\" built=\"%s\" chip=\"%s\" panel=\"%s%s\" up=\"%lu\"\n",
                  board_.deviceId(), BOARD.name, BRAINO_VERSION,
                  BuildStamp::describe(), BuildStamp::builtAt(),
                  ESP.getChipModel(),
                  GUME_PANEL_DRIVER, GUME_PANEL_INVERTED ? "+inv" : "",
                  (unsigned long)(millis() / 1000UL));
}
