#pragma once

#include <stdint.h>

/* Chess piece sprites -- GENERATED by tools/gen_chess_sprites.py from
 * tools/chess_pieces.svg. Do not edit.
 *
 * One 32x32 silhouette per piece, as rows of uint32 with bit 31 leftmost.
 * Colour is not stored: ChessGame::drawPiece() paints the same mask twice, once
 * offset in an edge colour and once in a fill colour, so one set of shapes
 * serves both sides and every theme -- and the two sides register exactly,
 * which separate drawings would not. */
namespace ChessSprites {

constexpr uint8_t SIZE = 32;

/** Indexed by piece kind - 1, matching PAWN..KING in ChessGame.h. */
extern const uint32_t MASK[6][SIZE];

}   // namespace ChessSprites
