#pragma once

/* GENERATED by tools/gen_cursive_glyphs.py -- do not edit. */

#include "CursiveGame.h"

extern const CursiveGame::Glyph CURSIVE_GLYPHS[];

/* The word-tracing set lives after all the letters in CURSIVE_GLYPHS.
 * CURSIVE_WORDS is the text of each, so the screen can print what it
 * is asking for -- Glyph::label holds one character and a word needs
 * more than that. */
extern const char* const CURSIVE_WORDS[];

/* The box these coordinates live in. Not square: see COORD_W in
 * tools/gen_cursive_glyphs.py. The game hands these to
 * LetterTracer::configure() so the mapping stays uniform. */
constexpr int16_t CURSIVE_COORD_W = 200;
constexpr int16_t CURSIVE_COORD_H = 156;

constexpr uint8_t CURSIVE_GLYPH_COUNT = 100;
constexpr uint8_t CURSIVE_WORD_FIRST = 52;
constexpr uint8_t CURSIVE_WORD_COUNT = 48;
