#pragma once

/* GENERATED by tools/gen_cursive_glyphs.py -- do not edit. */

#include "CursiveGame.h"

extern const CursiveGame::Glyph CURSIVE_GLYPHS[];

/* The word-tracing set lives after all the letters in CURSIVE_GLYPHS.
 * CURSIVE_WORDS is the text of each, so the screen can print what it
 * is asking for -- Glyph::label holds one character and a word needs
 * more than that. */
extern const char* const CURSIVE_WORDS[];

constexpr uint8_t CURSIVE_GLYPH_COUNT = 91;
constexpr uint8_t CURSIVE_WORD_FIRST = 52;
constexpr uint8_t CURSIVE_WORD_COUNT = 39;
