// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2026 iamankushpandit <https://github.com/iamankushpandit>
//
// Part of Braino! -- https://github.com/iamankushpandit/Gume
// Free software under GPL-3.0-or-later. Reusing any part of this file, in
// any work, must keep this notice, credit iamankushpandit as the
// author, and stay under the same licence with corresponding source
// offered. See LICENSE and NOTICE.md.

#pragma once

/* GENERATED by tools/gen_cursive_glyphs.py -- do not edit. */

#include "CursiveGame.h"

extern const CursiveGame::Glyph CURSIVE_GLYPHS[];

/* The word-tracing set lives after all the letters in CURSIVE_GLYPHS.
 * CURSIVE_WORDS is the text of each, so the screen can print what it
 * is asking for -- Glyph::label holds one character and a word needs
 * more than that. */
extern const char* const CURSIVE_WORDS[];

/* The box these coordinates live in. Not square: see COORD_W in
 * tools/gen_cursive_glyphs.py. The game hands these to
 * LetterTracer::configure() so the mapping stays uniform. */
constexpr int16_t CURSIVE_COORD_W = 200;
constexpr int16_t CURSIVE_COORD_H = 156;

constexpr uint8_t CURSIVE_GLYPH_COUNT = 101;
constexpr uint8_t CURSIVE_WORD_FIRST = 52;
constexpr uint8_t CURSIVE_WORD_COUNT = 49;
