#pragma once

#include "games/AboutApp.h"
#include "games/CinnamonGame.h"
#include "games/ColorMixGame.h"
#include "games/CoinFlipGame.h"
#include "games/CountingGame.h"
#include "games/DiceGame.h"
#include "games/ElementsGame.h"
#include "games/FingerCountGame.h"
#include "games/FlagGame.h"
#include "games/FractionGame.h"
#include "games/GreWordsGame.h"
#include "games/MathGame.h"
#include "games/MazeGame.h"
#include "games/MemoryGame.h"
#include "games/MicrokuGame.h"
#include "games/MoneyGame.h"
#include "games/MultiplicationGame.h"
#include "games/NearbyApp.h"
#include "games/NumberLineGame.h"
#include "games/ObjectAddGame.h"
#include "games/OddOneOutGame.h"
#include "games/PianoGame.h"
#include "games/ChessGame.h"
#include "games/SeaBattleGame.h"
#include "games/CursiveGame.h"
#include "games/LudoGame.h"
#include "games/BackgammonGame.h"
#include "games/PercentCircleGame.h"
#include "games/ProfileApp.h"
#include "games/ScoresApp.h"
#include "games/SequenceGame.h"
#include "games/SettingsApp.h"
#include "games/ShapeColorGame.h"
#include "games/SlidingPuzzleGame.h"
#include "games/SortGame.h"
#include "games/StateFlagGame.h"
#include "games/StateMapGame.h"
#include "games/StatesGame.h"
#include "games/SystemInfoApp.h"
#include "games/TicTacToeGame.h"
#include "games/TimeGame.h"
#include "games/TraceGame.h"
#include "games/WifiApp.h"
#include "games/WhackAMoleGame.h"

struct GameInstances {
    TicTacToeGame ticTacToe;
    MemoryGame memory;
    MathGame math;
    MultiplicationGame multiplication;
    TimeGame time;
    WhackAMoleGame whackAMole;
    CinnamonGame cinnamon;
    MicrokuGame microku;
    ShapeColorGame shapeColor;
    CountingGame counting;
    MoneyGame money;
    FractionGame fractions;
    MazeGame maze;
    SortGame sort;
    ColorMixGame colorMix;
    SlidingPuzzleGame slidingPuzzle;
    OddOneOutGame oddOneOut;
    SettingsApp settings;
    WifiApp wifi;
    ObjectAddGame objectAdd;
    FingerCountGame fingerCount;
    SequenceGame sequence;
    NumberLineGame numberLine;
    FlagGame flag;
    StatesGame states;
    TraceGame trace;
    StateFlagGame stateFlag;
    StateMapGame stateMap;
    PercentCircleGame percent;
    GreWordsGame greWords;
    DiceGame dice;
    CoinFlipGame coinFlip;
    ElementsGame elements;
    PianoGame piano;
    ChessGame chess;
    SeaBattleGame seaBattle;
    CursiveGame cursive;
    LudoGame ludo;
    BackgammonGame backgammon;
    ProfileApp profile;
    ScoresApp scores;
    AboutApp about;
    SystemInfoApp systemInfo;
    NearbyApp nearby;
};
