#include "GreWordTable.h"

/*
 * 250 high-frequency GRE words.
 *
 * Alphabetical, so the list is auditable at a glance, and spread across the
 * whole alphabet rather than clustered -- a table that runs abate..ascent is
 * an alphabetical prefix, not a vocabulary list, and a student working through
 * it would meet no word past "a".
 *
 * Glosses are deliberately short (~45 chars): they are rendered at font 1 as
 * quiz options across ~280px, and a definition that truncates is a definition
 * the student cannot choose between. Examples show the word in use, which is
 * what makes an abstract gloss stick.
 */
const GreWord GRE_WORDS[] = {
    {"abate", "v.", "lessen in intensity", "The storm abated by morning."},
    {"aberrant", "adj.", "departing from the normal", "His aberrant behaviour worried his family."},
    {"abscond", "v.", "leave hastily and secretly", "The cashier absconded with the takings."},
    {"abstruse", "adj.", "hard to understand", "The lecture grew abstruse after an hour."},
    {"accolade", "n.", "an award or expression of praise", "The film collected accolades everywhere."},
    {"acerbic", "adj.", "sharp and biting in tone", "Her acerbic review ended his career."},
    {"acquiesce", "v.", "accept reluctantly, without protest", "He acquiesced rather than prolong it."},
    {"acumen", "n.", "keen practical judgement", "Her business acumen saved the company."},
    {"admonish", "v.", "warn or reprimand gently", "The judge admonished the lawyer."},
    {"adulterate", "v.", "make impure by adding something", "The honey was adulterated with syrup."},
    {"aesthetic", "adj.", "concerned with beauty", "The building has real aesthetic merit."},
    {"affable", "adj.", "friendly and easy to talk to", "An affable host puts guests at ease."},
    {"aggrandize", "v.", "increase power or importance", "He used the office to aggrandize himself."},
    {"alacrity", "n.", "brisk and cheerful readiness", "She accepted with alacrity."},
    {"allay", "v.", "reduce fear or concern", "His calm tone allayed their worries."},
    {"amalgamate", "v.", "combine into one", "The two firms amalgamated last spring."},
    {"ambivalent", "adj.", "having mixed feelings", "She was ambivalent about moving abroad."},
    {"ameliorate", "v.", "make a bad situation better", "Aid can ameliorate but not end famine."},
    {"anachronism", "n.", "something out of its proper time", "The clock in the Roman play jars."},
    {"anomaly", "n.", "a deviation from the norm", "The reading was an anomaly, not a trend."},
    {"antipathy", "n.", "a deep-seated dislike", "His antipathy to crowds kept him home."},
    {"apathy", "n.", "lack of interest or concern", "Voter apathy decided the election."},
    {"aplomb", "n.", "self-confidence under pressure", "She handled the heckler with aplomb."},
    {"apocryphal", "adj.", "of doubtful authenticity", "The story is famous but apocryphal."},
    {"arcane", "adj.", "understood by very few", "The rules of the guild were arcane."},
    {"ardent", "adj.", "very enthusiastic or passionate", "An ardent supporter of the cause."},
    {"arduous", "adj.", "requiring great effort", "The ascent was long and arduous."},
    {"ascetic", "adj.", "severely self-disciplined", "He led an ascetic life in the hills."},
    {"assiduous", "adj.", "showing great care and persistence", "Her assiduous note-taking paid off."},
    {"assuage", "v.", "make an unpleasant feeling milder", "Nothing could assuage his guilt."},
    {"astute", "adj.", "shrewd, quick to see advantage", "An astute reading of the market."},
    {"attenuate", "v.", "reduce in force or value", "Distance attenuates the signal."},
    {"audacious", "adj.", "boldly daring", "An audacious plan that nearly worked."},
    {"augment", "v.", "make greater by adding", "She augmented her income by teaching."},
    {"auspicious", "adj.", "promising success", "An auspicious start to the season."},
    {"austere", "adj.", "severe or plain", "The room was clean and austere."},
    {"avarice", "n.", "extreme greed for wealth", "Avarice, not need, drove the scheme."},
    {"banal", "adj.", "lacking originality, boring", "The speech was banal and forgettable."},
    {"belie", "v.", "give a false impression of", "His calm face belied his panic."},
    {"bellicose", "adj.", "demonstrating aggression", "The bellicose speech alarmed diplomats."},
    {"bolster", "v.", "support or strengthen", "New data bolstered the argument."},
    {"bombastic", "adj.", "high-sounding but empty", "A bombastic address full of phrases."},
    {"brusque", "adj.", "abrupt in manner", "His brusque reply ended the chat."},
    {"bucolic", "adj.", "of pleasant countryside", "A bucolic scene of fields and sheep."},
    {"burgeon", "v.", "grow or increase rapidly", "The population burgeoned in a decade."},
    {"cacophony", "n.", "a harsh mixture of sounds", "A cacophony of horns filled the street."},
    {"callous", "adj.", "insensitive to suffering", "A callous disregard for the tenants."},
    {"candor", "n.", "openness and honesty", "He spoke with disarming candor."},
    {"capricious", "adj.", "given to sudden mood changes", "A capricious ruler, feared by all."},
    {"castigate", "v.", "reprimand severely", "The report castigated the regulator."},
    {"caustic", "adj.", "sarcastic in a scathing way", "Her caustic wit spared no one."},
    {"censure", "v.", "express severe disapproval", "The board censured its own chairman."},
    {"chicanery", "n.", "the use of trickery", "Legal chicanery delayed the trial."},
    {"circumspect", "adj.", "wary, unwilling to take risks", "Be circumspect about what you sign."},
    {"clandestine", "adj.", "kept secret", "A clandestine meeting after midnight."},
    {"coalesce", "v.", "come together to form one whole", "The factions coalesced into a party."},
    {"cogent", "adj.", "clear, logical and convincing", "A cogent case for the new policy."},
    {"commensurate", "adj.", "corresponding in size or degree", "Pay commensurate with experience."},
    {"compendium", "n.", "a concise collection of facts", "A compendium of medieval law."},
    {"complacent", "adj.", "smugly self-satisfied", "Success made the team complacent."},
    {"conciliatory", "adj.", "intended to placate", "He struck a conciliatory tone."},
    {"condone", "v.", "accept or forgive behaviour", "We cannot condone the deception."},
    {"conflagration", "n.", "an extensive destructive fire", "The conflagration razed three blocks."},
    {"congenial", "adj.", "pleasant, agreeable", "A congenial companion for the trip."},
    {"consternation", "n.", "anxiety or dismay", "To their consternation, the road closed."},
    {"contrite", "adj.", "feeling remorse", "A contrite apology, offered at last."},
    {"conundrum", "n.", "a confusing, difficult problem", "The scheduling conundrum defeated them."},
    {"corroborate", "v.", "confirm with evidence", "A second witness corroborated it."},
    {"cosmopolitan", "adj.", "familiar with many cultures", "A cosmopolitan city of many tongues."},
    {"craven", "adj.", "contemptibly lacking courage", "A craven retreat from the promise."},
    {"credulous", "adj.", "too ready to believe", "Credulous buyers lost their savings."},
    {"cryptic", "adj.", "mysterious in meaning", "He left a cryptic note on the desk."},
    {"culpable", "adj.", "deserving blame", "The report found the agency culpable."},
    {"cursory", "adj.", "hasty and not thorough", "Only a cursory glance at the figures."},
    {"dearth", "n.", "a scarcity or lack", "A dearth of qualified applicants."},
    {"debacle", "n.", "a sudden humiliating failure", "The launch was an expensive debacle."},
    {"decorum", "n.", "propriety of behaviour", "He observed decorum even when provoked."},
    {"deference", "n.", "humble submission and respect", "In deference to her age, they waited."},
    {"deleterious", "adj.", "causing harm", "The deleterious effect of long shifts."},
    {"denigrate", "v.", "criticise unfairly", "He denigrated rivals to look better."},
    {"derivative", "adj.", "imitative of another work", "The album is pleasant but derivative."},
    {"desiccate", "v.", "remove the moisture from", "Desiccated fruit keeps for months."},
    {"desultory", "adj.", "lacking a plan or purpose", "A desultory search through the files."},
    {"diatribe", "n.", "a forceful verbal attack", "A long diatribe against the press."},
    {"didactic", "adj.", "intended to teach, moralising", "The novel is heavy and didactic."},
    {"diffident", "adj.", "shy from lack of confidence", "Too diffident to state her case."},
    {"digress", "v.", "depart from the main subject", "He digressed into a long anecdote."},
    {"dilatory", "adj.", "slow to act", "The council was dilatory in replying."},
    {"disabuse", "v.", "free from a mistaken belief", "Let me disabuse you of that idea."},
    {"discern", "v.", "perceive or recognise", "She discerned a pattern in the noise."},
    {"discordant", "adj.", "disagreeing, harsh-sounding", "A discordant note in an easy meeting."},
    {"disparage", "v.", "represent as of little worth", "He disparaged the work in public."},
    {"disparate", "adj.", "essentially different in kind", "Two disparate accounts of one night."},
    {"dissemble", "v.", "conceal true motives", "He dissembled when asked directly."},
    {"disseminate", "v.", "spread widely", "The findings were disseminated online."},
    {"dogmatic", "adj.", "asserting opinion as if fact", "A dogmatic refusal to read the data."},
    {"dubious", "adj.", "hesitating, or of doubtful worth", "A dubious claim on a dubious receipt."},
    {"ebullient", "adj.", "cheerful and full of energy", "An ebullient host, greeting everyone."},
    {"eclectic", "adj.", "drawing ideas from many sources", "An eclectic collection of furniture."},
    {"efficacy", "n.", "the power to produce a result", "Trials tested the drug's efficacy."},
    {"effrontery", "n.", "insolent behaviour", "He had the effrontery to ask again."},
    {"egregious", "adj.", "outstandingly bad", "An egregious error in the accounts."},
    {"elicit", "v.", "draw out a response", "The question elicited only silence."},
    {"eloquent", "adj.", "fluent and persuasive", "An eloquent defence of the plan."},
    {"embellish", "v.", "add detail to make attractive", "He embellished the tale each telling."},
    {"empirical", "adj.", "based on observation, not theory", "Empirical evidence settled it."},
    {"emulate", "v.", "match or surpass by imitation", "Younger players emulate her style."},
    {"enervate", "v.", "drain of energy", "The heat enervated the whole crew."},
    {"engender", "v.", "give rise to", "The delay engendered real distrust."},
    {"enigma", "n.", "something puzzling", "His motive remains an enigma."},
    {"ephemeral", "adj.", "lasting a very short time", "Fame here is ephemeral."},
    {"equanimity", "n.", "calmness under strain", "She took the news with equanimity."},
    {"equivocate", "v.", "use ambiguous language to hide", "He equivocated instead of answering."},
    {"erudite", "adj.", "having great knowledge", "An erudite study of early maps."},
    {"esoteric", "adj.", "understood by only a few", "An esoteric branch of mathematics."},
    {"eulogy", "n.", "a speech of high praise", "He delivered the eulogy without notes."},
    {"exacerbate", "v.", "make worse", "Silence only exacerbated the rumours."},
    {"exculpate", "v.", "clear from blame", "New evidence exculpated the driver."},
    {"exigent", "adj.", "urgent, demanding", "Exigent circumstances forced the call."},
    {"exonerate", "v.", "absolve of blame", "The inquiry exonerated the pilot."},
    {"expedient", "adj.", "convenient though improper", "A politically expedient silence."},
    {"extol", "v.", "praise enthusiastically", "Reviewers extolled her first novel."},
    {"extraneous", "adj.", "irrelevant, unrelated", "Strip out the extraneous detail."},
    {"fastidious", "adj.", "very attentive to detail", "A fastidious editor, checking twice."},
    {"fatuous", "adj.", "silly and pointless", "A fatuous remark that helped nobody."},
    {"fervent", "adj.", "having intense feeling", "A fervent believer in the method."},
    {"flout", "v.", "openly disregard a rule", "Drivers flout the limit nightly."},
    {"foment", "v.", "stir up trouble", "Agitators fomented the unrest."},
    {"frugal", "adj.", "sparing with money or food", "A frugal household, and a happy one."},
    {"furtive", "adj.", "attempting to avoid notice", "A furtive glance toward the door."},
    {"garrulous", "adj.", "excessively talkative", "A garrulous neighbour, hard to escape."},
    {"germane", "adj.", "relevant to the matter", "That objection is not germane."},
    {"grandiloquent", "adj.", "pompous in language", "A grandiloquent toast nobody followed."},
    {"gregarious", "adj.", "fond of company", "Gregarious by nature, she knew everyone."},
    {"hackneyed", "adj.", "overused and unoriginal", "A hackneyed ending to a good film."},
    {"harangue", "n.", "a lengthy aggressive speech", "A harangue about the state of the roads."},
    {"iconoclast", "n.", "one who attacks cherished beliefs", "An iconoclast among cautious peers."},
    {"impetuous", "adj.", "acting quickly without thought", "An impetuous choice he regretted."},
    {"implacable", "adj.", "unable to be appeased", "An implacable opponent of the merger."},
    {"inchoate", "adj.", "just begun, not fully formed", "An inchoate plan, still a sketch."},
    {"incisive", "adj.", "clear and direct", "An incisive question ended the debate."},
    {"indigent", "adj.", "very poor", "Free care for indigent patients."},
    {"indolent", "adj.", "wanting to avoid activity", "An indolent afternoon by the river."},
    {"ineffable", "adj.", "too great to be put in words", "The ineffable relief of arriving home."},
    {"inexorable", "adj.", "impossible to stop", "The inexorable rise of the water."},
    {"ingenuous", "adj.", "innocent and unsuspecting", "An ingenuous question, honestly meant."},
    {"inimical", "adj.", "tending to obstruct or harm", "Conditions inimical to growth."},
    {"innocuous", "adj.", "harmless", "An innocuous comment, badly received."},
    {"insipid", "adj.", "lacking flavour or interest", "An insipid soup and an insipid speech."},
    {"intractable", "adj.", "hard to control or solve", "An intractable dispute over water."},
    {"intransigent", "adj.", "refusing to compromise", "Both sides remained intransigent."},
    {"inundate", "v.", "overwhelm or flood", "The office was inundated with calls."},
    {"irascible", "adj.", "easily angered", "An irascible editor, feared by juniors."},
    {"laconic", "adj.", "using very few words", "His laconic reply was a single word."},
    {"laud", "v.", "praise highly", "Critics lauded the restoration."},
    {"lethargic", "adj.", "sluggish and apathetic", "The heat left everyone lethargic."},
    {"levity", "n.", "humour, often inappropriate", "A moment of levity broke the tension."},
    {"lucid", "adj.", "clear and easy to understand", "A lucid account of a complex case."},
    {"magnanimous", "adj.", "generous, especially to a rival", "A magnanimous speech after losing."},
    {"malleable", "adj.", "easily influenced or shaped", "Gold is malleable; so are young minds."},
    {"maverick", "n.", "an independent-minded person", "A maverick who ignored house style."},
    {"mercurial", "adj.", "subject to sudden mood changes", "A mercurial temper, charming then cold."},
    {"meticulous", "adj.", "showing great attention to detail", "Meticulous records saved the project."},
    {"mitigate", "v.", "make less severe", "Shade mitigates the worst of the heat."},
    {"mollify", "v.", "appease the anger of", "A refund mollified the customer."},
    {"morose", "adj.", "sullen and ill-tempered", "He grew morose as the evening wore on."},
    {"mundane", "adj.", "dull, of the ordinary world", "The mundane business of filing forms."},
    {"nascent", "adj.", "just coming into existence", "A nascent industry, barely five years old."},
    {"nebulous", "adj.", "vague, ill-defined", "A nebulous promise of future help."},
    {"nefarious", "adj.", "wicked or criminal", "Nefarious dealings came to light."},
    {"neophyte", "n.", "a beginner", "A neophyte among seasoned climbers."},
    {"obdurate", "adj.", "stubbornly refusing to change", "The landlord remained obdurate."},
    {"obfuscate", "v.", "make unclear", "Jargon obfuscated a simple point."},
    {"obsequious", "adj.", "excessively flattering", "An obsequious aide, always agreeing."},
    {"occlude", "v.", "block or obstruct", "Cloud occluded the summit all day."},
    {"onerous", "adj.", "involving a heavy burden", "The onerous terms of the loan."},
    {"opprobrium", "n.", "harsh public criticism", "Public opprobrium followed the leak."},
    {"ostensible", "adj.", "stated but perhaps not true", "The ostensible reason was cost."},
    {"ostentatious", "adj.", "designed to impress", "An ostentatious display of wealth."},
    {"paragon", "n.", "a model of excellence", "A paragon of patience with children."},
    {"partisan", "adj.", "prejudiced in favour of a cause", "Partisan coverage of a routine vote."},
    {"paucity", "n.", "the presence of too little", "A paucity of evidence stalled the case."},
    {"pedantic", "adj.", "over-concerned with small detail", "A pedantic objection about commas."},
    {"penchant", "n.", "a strong liking", "A penchant for late-night walks."},
    {"perfunctory", "adj.", "done without care, as a duty", "A perfunctory nod and nothing more."},
    {"pernicious", "adj.", "having a harmful effect", "The pernicious effect of constant noise."},
    {"perspicacious", "adj.", "having keen insight", "A perspicacious reading of the mood."},
    {"petulant", "adj.", "childishly sulky", "A petulant refusal to shake hands."},
    {"placate", "v.", "make less angry", "Nothing could placate the crowd."},
    {"platitude", "n.", "a dull, overused remark", "The speech was a string of platitudes."},
    {"plausible", "adj.", "seeming reasonable", "A plausible but untrue explanation."},
    {"polemic", "n.", "a strong verbal attack", "A polemic against modern schooling."},
    {"pragmatic", "adj.", "dealing with things practically", "A pragmatic fix, not an elegant one."},
    {"precarious", "adj.", "not securely held, risky", "A precarious perch on the ledge."},
    {"predilection", "n.", "a preference", "A predilection for early mornings."},
    {"prescient", "adj.", "knowing events before they happen", "A prescient warning, ignored then."},
    {"prevaricate", "v.", "speak evasively", "He prevaricated under questioning."},
    {"pristine", "adj.", "in original, unspoilt condition", "A pristine copy of the first edition."},
    {"profligate", "adj.", "recklessly wasteful", "A profligate use of public money."},
    {"proliferate", "v.", "increase rapidly in number", "Copies proliferated across the network."},
    {"propensity", "n.", "a natural inclination", "A propensity to interrupt."},
    {"prosaic", "adj.", "commonplace, unromantic", "A prosaic cause for a strange light."},
    {"pugnacious", "adj.", "eager to argue or fight", "A pugnacious reply to mild criticism."},
    {"quiescent", "adj.", "in a state of inactivity", "The market stayed quiescent for months."},
    {"quixotic", "adj.", "idealistic and impractical", "A quixotic bid to save the theatre."},
    {"rebuke", "v.", "express sharp disapproval", "The chair rebuked him for shouting."},
    {"recalcitrant", "adj.", "stubbornly uncooperative", "A recalcitrant witness, saying nothing."},
    {"recondite", "adj.", "little known, abstruse", "A recondite point of grammar."},
    {"redolent", "adj.", "strongly suggestive or smelling of", "A room redolent of old books."},
    {"refute", "v.", "prove a statement wrong", "The data refuted his central claim."},
    {"reticent", "adj.", "unwilling to speak freely", "Reticent about his own part in it."},
    {"sagacious", "adj.", "having good judgement", "A sagacious choice of adviser."},
    {"salient", "adj.", "most noticeable or important", "The salient facts fit on one page."},
    {"sanguine", "adj.", "optimistic in a hard situation", "Sanguine about their chances, despite all."},
    {"scrupulous", "adj.", "very careful and honest", "Scrupulous about crediting sources."},
    {"soporific", "adj.", "tending to induce sleep", "A soporific lecture after lunch."},
    {"specious", "adj.", "seeming right but actually wrong", "A specious argument that fooled many."},
    {"sporadic", "adj.", "occurring at irregular intervals", "Sporadic rain all afternoon."},
    {"spurious", "adj.", "false, not genuine", "A spurious claim of authorship."},
    {"squander", "v.", "waste in a reckless manner", "He squandered a two-goal lead."},
    {"stoic", "adj.", "enduring hardship without complaint", "Stoic in the face of real pain."},
    {"strident", "adj.", "loud and harsh", "A strident tone that ended discussion."},
    {"substantiate", "v.", "provide evidence for", "Nothing substantiated the rumour."},
    {"superfluous", "adj.", "more than is needed", "Cut every superfluous word."},
    {"sycophant", "n.", "one who flatters for advantage", "Surrounded by sycophants, he heard nothing."},
    {"taciturn", "adj.", "saying very little", "A taciturn guide who pointed, not spoke."},
    {"tangential", "adj.", "only slightly relevant", "A tangential remark that derailed us."},
    {"tenacious", "adj.", "holding firmly, persistent", "A tenacious defence lasted an hour."},
    {"tenuous", "adj.", "very weak or slight", "A tenuous link between the two events."},
    {"timorous", "adj.", "showing a lack of courage", "A timorous knock at the door."},
    {"torpor", "n.", "a state of inactivity", "Afternoon torpor settled on the office."},
    {"tractable", "adj.", "easy to control or solve", "A tractable problem, given time."},
    {"transient", "adj.", "lasting only a short time", "A transient fault in the power supply."},
    {"trenchant", "adj.", "vigorous and incisive", "A trenchant analysis of the failure."},
    {"truculent", "adj.", "eager to argue, aggressive", "A truculent reply to a fair question."},
    {"turpitude", "n.", "depraved or wicked behaviour", "Dismissed for moral turpitude."},
    {"ubiquitous", "adj.", "present everywhere", "Screens are now ubiquitous."},
    {"umbrage", "n.", "offence or annoyance", "She took umbrage at the suggestion."},
    {"untenable", "adj.", "not able to be defended", "His position became untenable."},
    {"vacillate", "v.", "waver between options", "He vacillated for a week, then chose."},
    {"venerate", "v.", "regard with deep respect", "Students venerated the old professor."},
    {"veracity", "n.", "conformity to facts, accuracy", "Nobody questioned her veracity."},
    {"verbose", "adj.", "using more words than needed", "A verbose report nobody finished."},
    {"vicarious", "adj.", "experienced through another", "Vicarious pride in his son's success."},
    {"vilify", "v.", "speak of abusively", "The press vilified her for a week."},
    {"vindicate", "v.", "clear of blame or prove right", "Time vindicated the early sceptics."},
    {"virulent", "adj.", "extremely severe or hostile", "A virulent strain, and virulent abuse."},
    {"vociferous", "adj.", "expressing opinions loudly", "Vociferous objections from the back."},
    {"volatile", "adj.", "liable to change rapidly", "A volatile market and a volatile temper."},
    {"zealot", "n.", "a fanatical partisan", "A zealot for one narrow reading."},
};

/* Derived, never hand-counted. The previous table declared 200 as a literal
 * beside an array of a different length -- Progress would then have indexed
 * past the end. */
const uint16_t GRE_WORD_COUNT = sizeof(GRE_WORDS) / sizeof(GRE_WORDS[0]);

/* Progress keeps one byte per item in a fixed array (its private MAX_ITEMS,
 * currently 256) and clamps anything past it, so a longer table would silently make its tail unreachable --
 * those words would never be picked and never be revised. Catch that here
 * rather than wondering why "zealot" never appears. */
static_assert(sizeof(GRE_WORDS) / sizeof(GRE_WORDS[0]) <= 256,
              "GRE table exceeds Progress::MAX_ITEMS; later words would be unreachable");
