#include "StateData.h"

/* Sorted by postal code so lookups can binary-search. Tiers group by how
 * likely a player is to have heard of the state, matching the Easy/Medium/
 * Hard structure the flag game already uses. */
const StateFact STATE_FACTS[] = {
    { "AK", "Alaska", "Juneau", 1 },
    { "AL", "Alabama", "Montgomery", 3 },
    { "AR", "Arkansas", "Little Rock", 3 },
    { "AZ", "Arizona", "Phoenix", 2 },
    { "CA", "California", "Sacramento", 1 },
    { "CO", "Colorado", "Denver", 2 },
    { "CT", "Connecticut", "Hartford", 3 },
    { "DE", "Delaware", "Dover", 3 },
    { "FL", "Florida", "Tallahassee", 1 },
    { "GA", "Georgia", "Atlanta", 2 },
    { "HI", "Hawaii", "Honolulu", 1 },
    { "IA", "Iowa", "Des Moines", 3 },
    { "ID", "Idaho", "Boise", 3 },
    { "IL", "Illinois", "Springfield", 1 },
    { "IN", "Indiana", "Indianapolis", 2 },
    { "KS", "Kansas", "Topeka", 2 },
    { "KY", "Kentucky", "Frankfort", 3 },
    { "LA", "Louisiana", "Baton Rouge", 2 },
    { "MA", "Massachusetts", "Boston", 1 },
    { "MD", "Maryland", "Annapolis", 3 },
    { "ME", "Maine", "Augusta", 3 },
    { "MI", "Michigan", "Lansing", 2 },
    { "MN", "Minnesota", "Saint Paul", 2 },
    { "MO", "Missouri", "Jefferson City", 3 },
    { "MS", "Mississippi", "Jackson", 3 },
    { "MT", "Montana", "Helena", 3 },
    { "NC", "North Carolina", "Raleigh", 2 },
    { "ND", "North Dakota", "Bismarck", 3 },
    { "NE", "Nebraska", "Lincoln", 3 },
    { "NH", "New Hampshire", "Concord", 3 },
    { "NJ", "New Jersey", "Trenton", 2 },
    { "NM", "New Mexico", "Santa Fe", 3 },
    { "NV", "Nevada", "Carson City", 2 },
    { "NY", "New York", "Albany", 1 },
    { "OH", "Ohio", "Columbus", 2 },
    { "OK", "Oklahoma", "Oklahoma City", 3 },
    { "OR", "Oregon", "Salem", 2 },
    { "PA", "Pennsylvania", "Harrisburg", 2 },
    { "RI", "Rhode Island", "Providence", 3 },
    { "SC", "South Carolina", "Columbia", 3 },
    { "SD", "South Dakota", "Pierre", 3 },
    { "TN", "Tennessee", "Nashville", 2 },
    { "TX", "Texas", "Austin", 1 },
    { "UT", "Utah", "Salt Lake City", 2 },
    { "VA", "Virginia", "Richmond", 2 },
    { "VT", "Vermont", "Montpelier", 3 },
    { "WA", "Washington", "Olympia", 1 },
    { "WI", "Wisconsin", "Madison", 2 },
    { "WV", "West Virginia", "Charleston", 3 },
    { "WY", "Wyoming", "Cheyenne", 3 },
};

const uint8_t STATE_COUNT = 50;
