"""Stamp the branch and commit a build came from into the firmware.

A PlatformIO pre-build script, wired in from `[esp32_common]` so every
environment gets it. It answers one question that the version number cannot:
*which* build is on this board. `BRAINO_VERSION` is 5.0.0 across dozens of
flashes; the branch and the commit are what tell you whether the thing in your
hand is the release, or the branch you were mid-way through an hour ago.

Read `include/BuildStamp.h` before changing anything here -- the two halves of
this are deliberately split, and the reason is not obvious.

## These are written to a header, not injected as `-D`, and that is the point

The obvious implementation appends them to `CPPDEFINES`. This script did that
until 5.9.x, and the cost was measured rather than guessed:

    pio run -e app, nothing changed          66 s,    1 object
    pio run -e app, branch name different   333 s,  336 objects

Every object. PlatformIO folds the build flags into its build signature and
`env.Append(CPPDEFINES=...)` reaches the Arduino core and NimBLE as well as our
own sources -- so a commit hash, which changes on every commit by definition,
recompiled 165 NimBLE objects and 46 framework objects to change a string that
only `src/BuildStamp.cpp` reads. The old comment here defended that as "they
change when you move to a different commit, which is when the tree needed
rebuilding anyway". The tree did not: 89 of those 336 objects are ours, and
usually one of them is what actually changed.

It also meant CI could never cache anything. Every run is a new commit, so
every run was a cold build of every environment.

So the values go into a generated header instead. The include *path* is a
build flag and is constant, so it perturbs the signature once and never again;
the header's *contents* change freely, and only the one translation unit that
includes it is rebuilt. `src/BuildStamp.cpp` is deleted below on every build
anyway, for `__DATE__`/`__TIME__`, so in practice the stamp now costs exactly
the file it was always going to cost.

## The time is in that header too, and it has to be

It used to come from the compiler's `__DATE__`/`__TIME__`, with this script
deleting `BuildStamp.cpp.o` so they were always fresh. That stops working the
moment `build_cache_dir` is on: SCons restores the object from the cache rather
than compiling it -- the source has not changed, so it is a legitimate hit --
and the reported build time freezes at whenever the first build happened. It
was measured doing exactly that (`compiled=0` on a build meant to restamp it).

A stale build time is worse than none, because it is believed. So it is
generated here, and its changing on every build is now harmless: that is the
whole difference between a header and a flag.

The value is the build machine's local clock, in the shape `__DATE__ " "
__TIME__` used to produce, so the screens laying out against it are unaffected.
It identifies a build; it is not a timestamp to compute with.

## Where the values come from

`git` in the project directory, except on GitHub Actions, which checks out a
detached HEAD -- `git rev-parse --abbrev-ref HEAD` there says "HEAD" rather
than the branch anyone means. `GITHUB_HEAD_REF` (set on pull requests) and
`GITHUB_REF_NAME` (set on pushes) carry the real name, so they win when set.

A build from a source tarball has no `.git` at all. That is a legitimate way to
build this firmware, so a missing git is not an error: the stamp reads
"unknown", the About page says so plainly, and the build proceeds.
"""

import os
import subprocess
import time

Import("env")  # noqa: F821 -- injected by PlatformIO/SCons

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821

UNKNOWN = "unknown"


def git(*args):
    """Run a git command in the project dir, or return None if it cannot."""
    try:
        out = subprocess.run(
            ("git",) + args,
            cwd=PROJECT_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    text = out.stdout.decode("utf-8", "replace").strip()
    return text or None


def branch_name():
    """The branch, preferring CI's environment over a detached HEAD."""
    for var in ("GITHUB_HEAD_REF", "GITHUB_REF_NAME"):
        value = os.environ.get(var, "").strip()
        if value:
            return value
    name = git("rev-parse", "--abbrev-ref", "HEAD")
    if not name or name == "HEAD":
        # Detached outside CI -- a bisect, or a `git switch --detach`. The tag
        # or the commit is more use than the word "HEAD".
        return git("describe", "--tags", "--exact-match") or UNKNOWN
    return name


def short_commit():
    return git("rev-parse", "--short=7", "HEAD") or UNKNOWN


HEADER_NAME = "GumeBuildStamp.h"

HEADER_TEMPLATE = """#pragma once
/* GENERATED by tools/build_stamp.py on every build. Do not edit, and do not
 * check in -- it lives in the build directory. src/BuildStamp.cpp is the only
 * file that includes it. */
#define GUME_BUILD_BRANCH %s
#define GUME_BUILD_COMMIT %s
#define GUME_BUILD_TIME %s
"""


def quoted(value):
    """`value` as a C string literal.

    NOT `env.StringifyMacro()`, which escapes the quotes for a shell command
    line -- correct for a `-D`, and it lands in a header as `\\"dev\\"`, which
    is "stray '\' in program" and a build that fails on the first file.
    A branch name can legally contain neither of these characters, but writing
    a header is not the place to be relying on that.
    """
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def built_at():
    """The build machine's local clock, in the shape the screens expect.

    Deliberately the same width and shape `__DATE__ " " __TIME__` produced --
    "Sep  8 2026 22:15" -- because About and System Info lay out against it and
    this is a build-system change, not a redesign of what they show.
    """
    now = time.localtime()
    return "%s %2d %d %02d:%02d" % (
        time.strftime("%b", now), now.tm_mday, now.tm_year,
        now.tm_hour, now.tm_min)


def write_header(directory, branch, commit):
    """Write the generated header, and leave it alone if it already says this.

    Rewriting an unchanged file would be harmless -- SCons decides by content
    signature, not mtime -- but not rewriting it keeps `pio run` honest for
    anyone watching the file, and costs nothing.
    """
    path = os.path.join(directory, HEADER_NAME)
    wanted = HEADER_TEMPLATE % (quoted(branch), quoted(commit),
                                quoted(built_at()))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() == wanted:
                return path
    except OSError:
        pass
    if not os.path.isdir(directory):
        os.makedirs(directory)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(wanted)
    return path


def stamp():
    branch = branch_name()
    commit = short_commit()

    # The directory is derived from $BUILD_DIR, so it is per-environment and
    # constant for the life of that environment. That constancy is the whole
    # trick: the -I is a build flag and would invalidate the tree if it moved,
    # and it never moves.
    generated = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
    write_header(generated, branch, commit)
    env.Append(CPPPATH=[generated])  # noqa: F821

    # No object is deleted here any more, and deleting one would not work.
    # The old trick was to remove BuildStamp.cpp.o so SCons recompiled it and
    # picked up fresh __DATE__/__TIME__. With `build_cache_dir` on, SCons puts
    # the object straight back from the cache instead of compiling it -- the
    # source has not changed, so it is a hit -- and the build time freezes at
    # whenever the first build happened. Measured: `compiled=0` on a rebuild
    # that was supposed to restamp the clock. About would have gone on
    # reporting a time from days earlier, which is worse than no time at all
    # because it is believed.
    #
    # So the time is written into the generated header with the other two. It
    # changes on every build, which is exactly the property that made it
    # unacceptable as a `-D`; in a header it costs the one translation unit
    # that includes it and nothing else.

    print("Build stamp: %s @ %s" % (branch, commit))


stamp()
