#!/usr/bin/env python3
"""Write each supported board's pin table and pin diagram from its profile.

    python tools/gen_board_docs.py           # rewrite docs/boards/
    python tools/gen_board_docs.py --check   # fail if docs/boards/ is stale

Why generated
-------------
Board facts go stale in two ways, and this file removes one of them. The
vendor pages we learned them from move, change and vanish -- that is what the
source links and archive snapshots in each page are for. And a pin table typed
into a document drifts from the firmware the day somebody corrects a profile:
the dual-USB CYD's LED order and battery line were both wrong in its profile
for a whole release, and a hand-written table would have repeated the mistake
with more authority. So the table and the diagram are derived from the same two
places the firmware reads -- the board's `[board_*]` section in platformio.ini
and its profile header in include/boards/ -- and a page cannot disagree with
the build.

What each page gets, between its GENERATED markers:
  - a facts table: panel, touch, audio path, battery sense, flash, the
    firmware's BOARD_NAME, its device-id tag and its installer environment;
  - every GPIO the firmware uses, sorted, with what it is for;
  - the pin diagram, docs/boards/img/<BOARD_NAME>-pins.png, drawn here;
  - the printable case's render, if cases/<BOARD_NAME>/preview.png exists;
  - any photos of the board in docs/boards/img/<BOARD_NAME>-*.jpg|png.

Everything outside the markers -- how to tell the board apart, what has been
checked on hardware, the source links -- is written by hand.

The images are our own on purpose. The vendor pages state no licence, so their
photos and drawings are all-rights-reserved; the pages link to them instead.
"""

import argparse
import glob
import io
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs", "boards")
IMG = os.path.join(DOCS, "img")
BEGIN = "<!-- BEGIN GENERATED by tools/gen_board_docs.py -- do not edit by hand -->"
END = "<!-- END GENERATED -->"

DRIVERS = {"ILI9341_2_DRIVER": "ILI9341", "ILI9341_DRIVER": "ILI9341",
           "ST7789_DRIVER": "ST7789", "ST7796_DRIVER": "ST7796"}
SECTIONS = ("PanelProfile", "TouchProfile", "ButtonProfile", "SdProfile",
            "RgbLedProfile", "AudioProfile", "BatteryProfile", "MemoryProfile")

# Colour per subsystem, for the diagram. Fixed art colours, not a theme.
GROUPS = [
    ("Display", (52, 110, 200)),
    ("Touch", (40, 150, 110)),
    ("Audio", (190, 110, 30)),
    ("RGB LED", (175, 60, 130)),
    ("SD card", (110, 110, 110)),
    ("Battery", (160, 60, 50)),
    ("Key", (90, 90, 160)),
]


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def boards():
    """One dict per [board_*] section: name, header, driver, display pins."""
    ini = read(os.path.join(ROOT, "platformio.ini"))
    out = []
    for section, body in re.findall(r"^\[board_(\w+)\](.*?)(?=^\[|\Z)", ini, re.M | re.S):
        flags = dict(re.findall(r"-D\s+(\w+)(?:=(\S+))?", body))
        name = re.search(r'BOARD_NAME=\\"([^\\"]+)\\"', body)
        header = re.search(r'GUME_BOARD_HEADER=\\"([^\\"]+)\\"', body)
        if not (name and header):
            continue
        envs = re.findall(r"^\[env:(\w+)\](?:(?!^\[).)*?\$\{board_%s\.build_flags\}"
                          % re.escape(section), ini, re.M | re.S)
        product = [e for e in envs if e == "app" or e.startswith("app_")]
        out.append({
            "section": section,
            "name": name.group(1),
            "header": header.group(1),
            "env": product[0] if product else None,
            "driver": next((v for k, v in DRIVERS.items() if k in flags), "?"),
            "tft": {k: int(flags[k]) for k in ("TFT_CS", "TFT_DC", "TFT_SCLK",
                                               "TFT_MOSI", "TFT_MISO", "TFT_RST")
                    if flags.get(k, "").lstrip("-").isdigit()},
            "touch_on_display_bus": "TOUCH_CS" in flags,
        })
    return out


def profile(header):
    """The profile's fields, grouped by section, as strings."""
    text = read(os.path.join(ROOT, "include", header))
    m = re.search(r'BoardProfile\s+BOARD\s*=\s*\{\s*"([^"]*)",\s*"([^"]+)"', text)
    prof = {"tag": m.group(2) if m else "?",
            "capacitive": bool(re.search(r"#define\s+GUME_TOUCH_CAPACITIVE\s+1", text)),
            "dac": bool(re.search(r"#define\s+GUME_HAS_AUDIO_DAC\s+1", text)),
            "codec": bool(re.search(r"#define\s+GUME_HAS_AUDIO_CODEC\s+1", text))}
    section = None
    for line in text.splitlines():
        s = next((x for x in SECTIONS if re.match(r"\s*%s\s*\{" % x, line)), None)
        if s:
            section = s
            prof[section] = {}
            continue
        f = re.match(r"\s*/\*\s*(\w+)\s*\*/\s*(.+?),?\s*(//.*)?$", line)
        if f and section:
            prof[section][f.group(1)] = f.group(2).rstrip(",").strip()
    return prof


def pin(v):
    return int(v) if v is not None and re.fullmatch(r"-?\d+", v) and int(v) >= 0 else None


def pin_uses(b, p):
    """[(gpio, group, what)] for every pin the firmware drives or reads."""
    uses = []

    def add(v, group, what):
        g = v if isinstance(v, int) else pin(v)
        if g is not None and g >= 0:   # -1 is 'not connected'
            uses.append((g, group, what))

    t = b["tft"]
    for key, what in (("TFT_CS", "chip select"), ("TFT_DC", "data/command"),
                      ("TFT_SCLK", "SPI clock"), ("TFT_MOSI", "SPI MOSI"),
                      ("TFT_MISO", "SPI MISO"), ("TFT_RST", "reset")):
        add(t.get(key), "Display", what)
    panel = p.get("PanelProfile", {})
    add(panel.get("backlightPin"), "Display", "backlight")

    touch = p.get("TouchProfile", {})
    if p["capacitive"]:
        add(touch.get("sda"), "Touch", "I2C SDA")
        add(touch.get("scl"), "Touch", "I2C SCL")
        add(touch.get("irq"), "Touch", "interrupt")
        add(touch.get("reset"), "Touch", "reset")
    else:
        shared = " (shared with the display)" if b["touch_on_display_bus"] else ""
        add(touch.get("sclk"), "Touch", "SPI clock" + shared)
        add(touch.get("mosi"), "Touch", "SPI MOSI" + shared)
        add(touch.get("miso"), "Touch", "SPI MISO" + shared)
        add(touch.get("cs"), "Touch", "chip select")
        irq_used = touch.get("irqUsable", "true") == "true"
        add(touch.get("irq"), "Touch", "interrupt" + ("" if irq_used else " (not used)"))

    add(p.get("ButtonProfile", {}).get("bootPin"), "Key", "BOOT, which the firmware uses as Home")
    sd = p.get("SdProfile", {})
    for k, what in (("cs", "chip select"), ("sclk", "SPI clock"),
                    ("mosi", "SPI MOSI"), ("miso", "SPI MISO")):
        add(sd.get(k), "SD card", what)
    rgb = p.get("RgbLedProfile", {})
    for k, what in (("r", "red"), ("g", "green"), ("b", "blue")):
        add(rgb.get(k), "RGB LED", what)
    audio = p.get("AudioProfile", {})
    add(audio.get("speakerPin"), "Audio", "speaker (DAC out)")
    for k, what in (("i2sMclk", "I2S MCLK"), ("i2sBclk", "I2S BCLK"),
                    ("i2sWordSelect", "I2S LRCK"), ("i2sDataOut", "I2S data out"),
                    ("i2sDataIn", "I2S data in")):
        add(audio.get(k), "Audio", what)
    active_low = audio.get("ampEnableActiveLow") == "true"
    add(audio.get("ampEnablePin"), "Audio",
        "amplifier enable" + (" (active low)" if active_low else ""))
    batt = p.get("BatteryProfile", {})
    ratio = batt.get("dividerRatio", "").rstrip("f")
    add(batt.get("adcPin"), "Battery", "voltage sense (%s:1 divider)" % ratio.rstrip("0").rstrip(".")
        if ratio else "voltage sense")
    return sorted(uses, key=lambda u: (u[0], [g for g, _ in GROUPS].index(u[1])))


def facts(b, p):
    panel = p.get("PanelProfile", {})
    touch = p.get("TouchProfile", {})
    audio = p.get("AudioProfile", {})
    flash = p.get("MemoryProfile", {}).get("flashBytes", "")
    mb = re.match(r"(\d+)u?\s*\*\s*1024", flash)
    if p["codec"]:
        sound = "ES8311 codec over I2S (I2C address %s)" % audio.get("codecI2cAddress", "?")
    elif p["dac"]:
        sound = "built-in DAC on GPIO%s, into an onboard amplifier" % audio.get("speakerPin")
    else:
        sound = "none"
    batt = pin(p.get("BatteryProfile", {}).get("adcPin"))
    rows = [
        ("Firmware name (`BOARD_NAME`)", "`%s`" % b["name"]),
        ("Installer / PlatformIO environment", "`%s`" % b["env"] if b["env"] else "none"),
        ("Device-id tag", "`%s-...`" % p["tag"]),
        ("Panel", "%s x %s, %s driver%s" % (panel.get("nativeWidth"), panel.get("nativeHeight"),
                                           b["driver"], ", colours inverted at runtime"
                                           if panel.get("invertColours") == "true" else "")),
        ("Touch", "capacitive, I2C" if p["capacitive"] else
         "resistive XPT2046, %s" % ("on the display's SPI bus" if b["touch_on_display_bus"]
                                    else "its own bit-banged SPI bus")),
        ("Sound", sound),
        ("Battery sense", "GPIO%d" % batt if batt is not None
         else "**none** -- no battery badge; run it from USB power"),
        ("Flash", "%s MB" % mb.group(1) if mb else flash or "?"),
    ]
    return rows


def diagram(b, p, uses, out_path):
    """A GPIO card: one row per pin, coloured by what it is for."""
    def font(size, bold=False):
        for name in (("consolab.ttf", "consola.ttf", "DejaVuSansMono-Bold.ttf")
                     if bold else ("consola.ttf", "DejaVuSansMono.ttf")):
            try:
                return ImageFont.truetype(name, size)
            except OSError:
                pass
        return ImageFont.load_default()

    title_f, row_f, small_f = font(22, True), font(16), font(13)
    row_h, pad = 26, 18
    subtitle = ("GPIO use, generated from include/%s and platformio.ini [board_%s]"
                % (b["header"], b["section"]))
    probe = ImageDraw.Draw(Image.new("RGB", (1, 1)))
    longest = max([probe.textlength(subtitle, font=small_f)] +
                  [210 + probe.textlength(w, font=row_f) for _g, _grp, w in uses])
    width = int(max(560, longest + 2 * pad))
    height = pad * 2 + 70 + row_h * len(uses) + 40
    img = Image.new("RGB", (width, height), (250, 250, 247))
    d = ImageDraw.Draw(img)
    d.text((pad, pad), b["name"], font=title_f, fill=(30, 30, 30))
    d.text((pad, pad + 32), subtitle, font=small_f, fill=(110, 110, 110))
    colour = dict(GROUPS)
    y = pad + 64
    for gpio, group, what in uses:
        c = colour[group]
        d.rounded_rectangle((pad, y + 3, pad + 76, y + row_h - 3), 5, fill=c)
        d.text((pad + 10, y + 5), "GPIO%-2d" % gpio, font=row_f, fill=(255, 255, 255))
        d.text((pad + 92, y + 5), group, font=row_f, fill=c)
        d.text((pad + 210, y + 5), what, font=row_f, fill=(40, 40, 40))
        y += row_h
    x = pad
    for group, c in GROUPS:
        if any(u[1] == group for u in uses):
            d.rectangle((x, y + 16, x + 12, y + 28), fill=c)
            d.text((x + 17, y + 14), group, font=small_f, fill=(60, 60, 60))
            x += 30 + int(d.textlength(group, font=small_f))
    buf = io.BytesIO()
    # Flat colours and text: a small palette loses nothing and quarters the file.
    img.convert("P", palette=Image.ADAPTIVE, colors=48).save(buf, "PNG", optimize=True)
    return buf.getvalue()


def photo_metadata(path):
    """What a photo carries besides pixels: EXIF, XMP, ICC text, PNG text.

    A phone photo's EXIF routinely holds the GPS position it was taken at, the
    phone's make and serial, and sometimes the owner's name -- which is
    exactly what CLAUDE.md's "no identifiers in this repository" rule forbids.
    A board photo needs none of it.
    """
    with Image.open(path) as im:
        found = [k for k in ("exif", "xmp", "XML:com.adobe.xmp", "comment", "photoshop")
                 if im.info.get(k)]
        if im.getexif():
            found.append("EXIF tags")
        found += [k for k in im.info if k not in ("dpi", "gamma", "transparency",
                                                 "icc_profile", "jfif", "jfif_version",
                                                 "jfif_unit", "jfif_density", "progressive",
                                                 "progression", "adobe", "adobe_transform")
                  and k not in found]
    return sorted(set(found))


def strip_metadata(path):
    """Re-save the pixels alone: no EXIF, no GPS, no text chunks."""
    with Image.open(path) as im:
        pixels = im.convert("RGB") if im.mode not in ("RGB", "L") else im.copy()
    if path.lower().endswith(".png"):
        pixels.save(path, "PNG", optimize=True)
    else:
        pixels.save(path, "JPEG", quality=90, optimize=True)


def photos_of(name):
    return sorted(f for f in glob.glob(os.path.join(IMG, name + "-*"))
                  if re.search(r"\.(jpe?g|png)$", f, re.I) and not f.endswith("-pins.png"))


def block(b, p, uses):
    lines = [BEGIN, "", "### From the firmware profile", "",
             "| | |", "|---|---|"]
    lines += ["| %s | %s |" % r for r in facts(b, p)]
    lines += ["", "| GPIO | Used for |", "|---|---|"]
    merged = {}
    for gpio, group, what in uses:
        merged.setdefault(gpio, []).append("%s: %s" % (group, what))
    lines += ["| %d | %s |" % (g, "; ".join(w)) for g, w in sorted(merged.items())]
    lines += ["", "![GPIO use on the %s](img/%s-pins.png)" % (b["name"], b["name"])]
    case = os.path.join(ROOT, "cases", b["name"], "preview.png")
    if os.path.exists(case):
        lines += ["", "The printable case, from [cases/%s](../../cases/%s/):" % (b["name"], b["name"]),
                  "", '<img src="../../cases/%s/preview.png" width="420" alt="Case for the %s">'
                  % (b["name"], b["name"])]
    photos = photos_of(b["name"])
    lines += ["", "### Photos", ""]
    if photos:
        lines += ['<img src="img/%s" width="360" alt="%s">' % (os.path.basename(f), b["name"])
                  for f in photos]
    else:
        lines += ["None yet. Add your own as `docs/boards/img/%s-front.jpg` (and `-back.jpg`)"
                  % b["name"], "and re-run `python tools/gen_board_docs.py`."]
    lines += ["", END]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if anything is stale")
    args = ap.parse_args()
    stale = []
    for b in boards():
        p = profile(b["header"])
        uses = pin_uses(b, p)
        png_path = os.path.join(IMG, "%s-pins.png" % b["name"])
        png = diagram(b, p, uses, png_path)
        page = os.path.join(DOCS, "%s.md" % b["name"])
        if not os.path.exists(page):
            stale.append("%s has no page (%s)" % (b["name"], os.path.relpath(page, ROOT)))
            continue
        text = read(page)
        if BEGIN not in text or END not in text:
            stale.append("%s has no GENERATED markers" % os.path.relpath(page, ROOT))
            continue
        new = text[:text.index(BEGIN)] + block(b, p, uses) + text[text.index(END) + len(END):]
        old_png = open(png_path, "rb").read() if os.path.exists(png_path) else None
        for photo in photos_of(b["name"]):
            meta = photo_metadata(photo)
            if meta and args.check:
                stale.append("%s carries metadata (%s) -- it can hold a GPS position "
                             "or a name" % (os.path.relpath(photo, ROOT), ", ".join(meta)))
            elif meta:
                strip_metadata(photo)
                print("stripped %s from %s" % (", ".join(meta), os.path.relpath(photo, ROOT)))
        if args.check:
            if new != text:
                stale.append("%s is out of date" % os.path.relpath(page, ROOT))
            if old_png is None:
                stale.append("%s is missing" % os.path.relpath(png_path, ROOT))
        else:
            os.makedirs(IMG, exist_ok=True)
            with open(page, "w", encoding="utf-8", newline="\n") as f:
                f.write(new)
            with open(png_path, "wb") as f:
                f.write(png)
            print("wrote %s and %s" % (os.path.relpath(page, ROOT), os.path.relpath(png_path, ROOT)))
    if stale:
        print("Board docs are out of step with the profiles:\n  - " + "\n  - ".join(stale)
              + "\nRun: python tools/gen_board_docs.py")
        return 1
    if args.check:
        print("Board docs: clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
