"""
Generate src/games/CountryData.cpp for GoodTime Kids.

    python tools/gen_country_facts.py

Country NAMES and artwork come from the map-n-flag library. This table adds
only what map-n-flag does not carry: capital city, continent, and a difficulty
tier for the kids' games.

Source data: https://github.com/mledoze/countries (ODbL). Only capital and
region/subregion fields are used, ASCII-folded so they render in the default
TFT_eSPI fonts.
"""
from __future__ import annotations

import json
import unicodedata
import urllib.request
from pathlib import Path

DATA_URL = "https://raw.githubusercontent.com/mledoze/countries/master/countries.json"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "games" / "CountryDataTable.cpp"
CACHE = ROOT / "tools" / "countries_cache.json"

# The 193 UN member states + Holy See + Palestine -- matches map-n-flag's
# "un195" scope exactly, so every entry here has a flag in the library.
UN195 = """
AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG
BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG
SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID
IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW
MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO
OM PK PW PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG
SK SI SB SO ZA SS ES LK SD SR SE CH SY TJ TZ TH TL TG TO TT TN TR TM TV UG UA
AE GB US UY UZ VU VE VN YE ZM ZW VA PS
""".split()

# Tier 1: the ~30 a young child is most likely to have heard of.
TIER1 = """
US GB FR DE IT ES CA MX BR AR CN JP KR IN RU AU NZ EG ZA NG KE GR PT NL CH SE
NO IE TR TH
""".split()

# Tier 2: adds another ~32 well-known countries (62 total).
TIER2 = TIER1 + """
BE AT DK FI PL UA CL CO PE ID VN PH MY SG PK BD MA ET GH SA AE IL IQ IR QA CU
JM IS HR CZ HU RO
""".split()

# Kept short: "North America" truncates to "North Americ." in the game's
# 100px continent buttons.
CONTINENTS = ["Africa", "Asia", "Europe", "N. America", "S. America", "Oceania"]


def ascii_fold(s: str) -> str:
    s = s.replace("’", "'").replace("‘", "'")
    special = {"Ø": "O", "ø": "o", "Æ": "AE", "æ": "ae",
               "Ð": "D", "ð": "d", "Þ": "Th", "þ": "th",
               "Ł": "L", "ł": "l", "ß": "ss"}
    s = "".join(special.get(c, c) for c in s)
    s = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))
    return s.encode("ascii", "ignore").decode("ascii")


def continent_of(entry: dict) -> int:
    region = entry.get("region")
    sub = entry.get("subregion") or ""
    if region == "Africa":
        return 0
    if region == "Asia":
        return 1
    if region == "Europe":
        return 2
    if region == "Oceania":
        return 5
    if region == "Americas":
        return 4 if sub == "South America" else 3
    raise ValueError(f"unmapped region for {entry['cca2']}: {region}/{sub}")


def load_dataset() -> list:
    if CACHE.exists():
        return json.loads(CACHE.read_text(encoding="utf-8"))
    print(f"downloading {DATA_URL}")
    with urllib.request.urlopen(DATA_URL, timeout=120) as r:
        raw = r.read().decode("utf-8")
    CACHE.write_text(raw, encoding="utf-8")
    return json.loads(raw)


def main() -> None:
    data = load_dataset()
    by_code = {c["cca2"]: c for c in data}

    rows = []
    for code in sorted(UN195):
        e = by_code.get(code)
        if e is None:
            raise SystemExit(f"{code} missing from dataset")
        caps = e.get("capital") or []
        if not caps:
            raise SystemExit(f"{code} has no capital")
        capital = ascii_fold(caps[0])
        cont = continent_of(e)
        tier = 1 if code in TIER1 else (2 if code in TIER2 else 3)
        rows.append((code, capital, cont, tier))

    t1 = sum(1 for r in rows if r[3] == 1)
    t2 = sum(1 for r in rows if r[3] <= 2)
    print(f"{len(rows)} countries | tier1={t1} tier2(cumulative)={t2} tier3={len(rows)}")
    for i, name in enumerate(CONTINENTS):
        print(f"  {name:15s} {sum(1 for r in rows if r[2] == i)}")

    with OUT.open("w", encoding="utf-8") as f:
        f.write("""/*
 * Generated by tools/gen_country_facts.py -- DO NOT EDIT BY HAND.
 *
 * Capital cities and continents for the 195 countries carried by the
 * map-n-flag library. Country names and artwork come from map-n-flag itself;
 * this table only adds what that library does not store.
 *
 * Capital/region data derived from https://github.com/mledoze/countries (ODbL),
 * ASCII-folded for the built-in TFT_eSPI fonts.
 */
#include "CountryData.h"
#include <string.h>
#include <ctype.h>

const char* const CONTINENT_NAMES[CONTINENT_COUNT] = {
""")
        for name in CONTINENTS:
            f.write(f'    "{name}",\n')
        f.write("};\n\n")

        f.write("/* Sorted by ISO code so lookup can binary-search. */\n")
        f.write("const CountryFact COUNTRY_FACTS[] = {\n")
        for code, capital, cont, tier in rows:
            f.write(f'    {{ "{code}", "{capital}", {cont}, {tier} }},\n')
        f.write("};\n\n")
        f.write(f"const uint16_t COUNTRY_FACT_COUNT = {len(rows)};\n")

    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
