/* The generated header MUST come before BuildStamp.h, whose "unknown"
 * fallbacks are guarded on these macros not already existing. It is written
 * into the build directory by tools/build_stamp.py, so it is absent when
 * something other than PlatformIO compiles this file -- an IDE indexer, a
 * unit-test harness -- and __has_include is what lets that keep working. */
#if defined(__has_include)
#  if __has_include(<GumeBuildStamp.h>)
#    include <GumeBuildStamp.h>
#  endif
#endif

#include "BuildStamp.h"

/* This translation unit exists to hold `__DATE__` and `__TIME__`, and it is
 * deleted from the build directory before every build by
 * `tools/build_stamp.py` so those two are always this build's. Keep it small:
 * it is recompiled every single time, unlike the rest of the tree.
 *
 * Nothing here allocates. The strings are literals or one fixed buffer, per the
 * memory rule -- these are read by About and by System Info's Device tab, and a
 * screen that rebuilds a `String` to say what it is would be an odd place to
 * start churning the heap. */

namespace BuildStamp {

const char* branch() {
    return GUME_BUILD_BRANCH;
}

const char* commit() {
    return GUME_BUILD_COMMIT;
}

const char* describe() {
    /* Adjacent string literals, so this is one constant in flash rather than a
     * concatenation done at runtime. */
    return GUME_BUILD_BRANCH " @ " GUME_BUILD_COMMIT;
}

const char* builtAt() {
    /* Generated by tools/build_stamp.py into the header above, in the shape
     * `__DATE__ " " __TIME__` used to produce ("Sep  8 2026 22:15"), seconds
     * dropped -- they are noise for identifying a build and cost width on a
     * 240px panel.
     *
     * It was assembled here from the compiler's own __DATE__/__TIME__ until
     * `build_cache_dir` arrived, at which point SCons began restoring this
     * object from the cache instead of recompiling it, and the reported time
     * froze at the first build. A literal cannot go stale, and it costs 18
     * bytes of static RAM less than the buffer it replaces. */
    return GUME_BUILD_TIME;
}

}  // namespace BuildStamp
